"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d*pux4#t0ysfs2cfatq4@di$@_g4ur9*jsc^kh=x(bgqs++@yv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方擴充套件(剛剛透過 uv add 安裝的套件)
    'rest_framework', # 建立 API
    'rest_framework.authtoken',  # Token 驗證必備
    'corsheaders',  # 處理跨域請求
    'drf_spectacular', # 新套件，要重新建置 Docker 映像檔
 
    # Auth & Allauth
    'dj_rest_auth',              # 提供 REST 架構的登入、註冊與密碼管理 API
    'django.contrib.sites',      # allauth 依賴 (需要設定 SITE_ID)
    'allauth',                   # 處理使用者驗證的核心套件
    'allauth.account',           # 管理一般帳號 (註冊、登入、Email 驗證)
    'allauth.socialaccount',     # 處理第三方登入 (Google, FB 等)，即使暫不用也建議保留
    'dj_rest_auth.registration', # 提供註冊相關的 REST API 端點
 
    # 自訂義的應用程式
    # 剛建立的本地 App，在此註冊後 Django 才能識別其模型與路由。
    'api',  
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 處理跨域請求的中介軟體，應放在 SecurityMiddleware 之前。
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # 讓 allauth 能夠在每個 Request 中存取 User 物件
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# 允許所有來源進行跨域請求，開發階段使用。
CORS_ALLOW_ALL_ORIGINS = True

# Django REST Framework 設定
REST_FRAMEWORK = {
    # 指定預設的 Schema 生成器為 drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Spectacular 設定 (API 文件資訊)
SPECTACULAR_SETTINGS = {
    'TITLE': 'Dog Project API',
    'DESCRIPTION': '這是 Dog Project 的後端 API 文件，提供狗狗資料的查詢與操作功能。',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # 在 API 文件頁面中隱藏 Schema 本身的端點
    # 其他設定可參考官方文件
}

# =========================================
# Auth & DRF Settings
# =========================================

# 1. 啟用 Token 驗證機制
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication', 
    ),
}

# 2. Allauth 必要設定
SITE_ID = 1  # 這是 django.contrib.sites 需要的

# 3. 註冊與登入行為設定
ACCOUNT_EMAIL_VERIFICATION = 'none'  # 開發階段先不強制驗證 Email
ACCOUNT_AUTHENTICATION_METHOD = 'username' # 使用使用者名稱登入
ACCOUNT_EMAIL_REQUIRED = False

# 4. Email 後端 (開發用，不會真的寄信，只會印在終端機)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'